### PR TITLE
Updates to ProgrammingArduino.ino regarding new module version KCX_BT_EMITTER v1.7

### PR DESCRIPTION
**Pull request by pandel**
Hi!

I changed some of your code to make it work with the current available module version v1.7. The most important changes are

- initial baud rate is 115200, the module initializes like that
- NUMWAIT to 500, as the new module is fast enough
- changes reflecting the new AT command syntax
- sending of commands in line mode (aka println), the current module does not like raw data
- added some more menu options for convenience
- added a partially translated specs pdf with the current set of AT commands

There are even more useful AT commands, like setting volume, baud rate and such. I did not integrate them in these first changes, but they might be useful for future development.

And perhaps you may want to create a new branch for people to select which version they'd like to use.

Regards,
Holger

### CODE REVIEW

**Comment by Mark-MDO47** [comment]
Holger - 
I just glanced over it and this looks great! I would like to try it but right now I don't have any V1.7 parts; I will order some. I also like your idea of having branches that work with different hardware versions.
In the next week I will go ahead and create two branches here, one for V1.1 (also works on some parts I have that are labeled V1.2) and one for V1.7. I will also put a pointer to your https://github.com/pandel/BluetoothAudioTransmitter_KCX_BT_EMITTER.
Thanks for the good work!
Mark

**Comment by Mark-MDO47** [comment]
Holger -
Status - I have ordered some V1.7 parts; they are scheduled to arrive in 2 weeks or so.
I looked more at the changes and had a question.
Why change cmd_SCAN from "AT+SCAN" to "AT+PAIR"? Would it be better to also have a cmd_PAIR and have that be part of a numbered selection? I used "AT+SCAN" to find the MAC addresses of available Bluetooth devices so I could copy/paste this information into the VMLINK. My goal was to set up the KCX_BT_EMITTER so it would automatically connect to a speaker each time it powered on and not connect to Bluetooth devices that were not in the VMLINK. Is there a way with your code to get this information so I can put it in the VMLINK?
Thanks!
Mark

**Comment by pandel** [comment]
Hi Mark!

I changed from AT+SCAN to AT+PAIR, because SCAN isn't available anymore, see reference doc, and I was too lazy to rename every code fragment - you are right, I should have done that to be more clear in this regard.

FYI, the current module behaves as follows:

- has never been connected: immediately starts scan and pairs with the first available receiver
- force it to restart SCAN: only via AT+PAIR (see doc, AT+PAIR is the same as pressing the button on the module)

For manual setup I think you have to know the receiver MAC in advance to set it up completely and are not able to scan and then decide what to do. From what you wrote I assume that the old module gave a list of MAC addresses and you could choose one. This does not work with the new module I assume, at least, I could not observe such behaviour. But I must admit, I don't have many different BT receivers to test with. I only have a cheap receiver module and a real JBL box (but the JBL has to be put into pairing mode after every restart of the KCX_BT_EMITTER, I think it is because the module simply lacks a "full" BT pairing mode and just "remembers" MAC addresses it has seen before and tries to reconnect).

As background info, my intention to use this module is to send audio files from an Arduino-DFPlayer-combo in a helmet to a receiver inside the body part of a cosplay costume to avoid having to route a lot of cables inside and through the neck. In this case, the simple receiver is more than enough in my use case.

Besides, the new module can also be set into receiver mode. I did not try it, but this might be interesting, too. You can setup a jumper on the board to change from emitter to receiver, but there are also AT+ commands to achieve this. Perhaps that might be interesting, too.

Regards,
Holger

**Comment by Mark-MDO47** [comment]
Holger -

Thanks for the explanation!

As soon as I get a few hours together I will accept your pull request and put it in branch KCX_BT_EMITTER_V1.7. I have already created a branch KCX_BT_EMITTER_V1.1 for the old code.

This is the first pull request I have ever accepted, so if you have advice please let me know. I want to be sure you get full credit for your work.

 It appears that the pull request is from the v1.7 branch of your repository to the master branch of my repository. I plan to accept this and then make the branch KCX_BT_EMITTER_V1.7 as mentioned above. I think this will probably bring your commit comments along.

After that I want to adjust the README.md files in each branch to explain what is going on.

Also I would like to change the variable name cmd_SCAN to cmd_PAIR to match its new function. Eventually I would want to have the KCX_BT_EMITTER_V1.7 branch have comments for the new V1.7 commands instead of the comments for the old V1.1 commands, but this will take some time.

When I get my V1.7 parts I hope to do some experimenting to see if there is some way to get the scan info and maybe experiment with some of the new options.

If I can't find a way to get the MAC address with V1.7, I still have a bunch of V1.1 parts in my parts bin so I can still get the MAC addresses from them. BTW if you want a couple of these V1.1 parts, I would send them if there is any way you can let me know where to ship them without broadcasting your address to the world.

Enjoy!
Mark

**Comment by pandel** [comment]
Hey!

No need to give any credit, I am glad I can help 🤗 ! But I am definitely interested in seeing if your v1.7 parts behave the same as mine, so that we can judge if my changes are generally compatible or not.

The MAC addresses are shown during scan, but what I don't know is (as I was not able to test it), if you get to see more then the one the device chose during first connect.

Regarding pull request: accepting a pull request is really simple in the first place, but I don't know if you can reorder my pull request to your new branch. It is also possible that you reject my pull request and I send a new one to your new v1.7 branch. Tell me what you like more and what is easier for you.

Bye :-)

**Pull request merged**
